version: '3.8'
services:
  backend:
    build: ./
    container_name: todo-list
    restart: always
    ports: 
      - 3000:3000
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - local
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - local
networks:
  local: